name: CMake CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build-type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_TESTS=ON
      
      - name: Build
        run: |
          cmake --build build --config ${{ matrix.build-type }} --parallel
      
      - name: Run tests
        working-directory: build
        run: |
          ctest --output-on-failure -C ${{ matrix.build-type }}
      
      - name: Prepare artifacts (Linux)
        if: runner.os == 'Linux' && matrix.build-type == 'Release'
        run: |
          mkdir -p artifacts/linux
          cp build/bin/rats artifacts/linux/
          cp build/lib/liblibrats.a artifacts/linux/
          cp -r src/*.h artifacts/linux/
      
      - name: Prepare artifacts (Windows)
        if: runner.os == 'Windows' && matrix.build-type == 'Release'
        run: |
          mkdir -p artifacts/windows
          cp build/bin/Release/rats.exe artifacts/windows/
          cp build/lib/Release/librats.lib artifacts/windows/
          cp src/*.h artifacts/windows/
      
      - name: Upload artifacts (Linux)
        if: runner.os == 'Linux' && matrix.build-type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: librats-linux-${{ github.sha }}
          path: artifacts/linux/
          retention-days: 30
      
      - name: Upload artifacts (Windows)
        if: runner.os == 'Windows' && matrix.build-type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: librats-windows-${{ github.sha }}
          path: artifacts/windows/
          retention-days: 30
